steps:
  # build executable
- name: "gcr.io/cloud-builders/dotnet"
  args: ["publish", "-c", "Release", "-r", "ubuntu.16.10-x64", "./Town Crier", "-o", "./../build"] 
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: 
  - "build"
  - "-t"
  - "gcr.io/$PROJECT_ID/town-crier" 
  - "."
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/town-crier"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=pod.yaml
  - --image=gcr.io/$PROJECT_ID/town-crier
  - --location=australia-southeast1-a
  - --cluster=agones-australia